config:
  target: 'http://localhost:8080/'
  http:
    pool: 100
  phases:
    - duration: 10
      arrivalRate: 500
  defaults:
    headers:
      Connection: 'keep-alive'
scenarios:
  - flow:
    - get:
        url: "/tmp/filex.txt"

    